### ISSUE TITLE
Replace js script tag with cdn

### ISSUE THREAD

**Issue by thewhistledev** [vultrex/probable-broccoli#2]
https://github.com/vultrex/probable-broccoli/blob/b949ea3735b68198ae40c6df4e8a9276ac7ba02c/index.html#L75

**Now this project has been pushed to github you can now use github's raw feature to grab the bs-init.js file and use github as a cdn**
```
https://raw.githubusercontent.com/vultrex/probable-broccoli/main/assets/js/bs-init.js
```

**Comment by kakarot-dev** [comment]
Thanks for the idea, bro!
Would love to see a pr bout this haha :)
